version: '3.7'
services:
  daemon:
    command: npm run dev
    volumes:
      - ./daemon/src:/app/src
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
