version: '3.7'
services:
  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: "no"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 6h; done'"
  daemon:
    build: ./daemon
    restart: unless-stopped
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - STAGING
      - EMAIL
      - SMTP_USERNAME
      - SMTP_PASSWORD
